const CONFIG=window.LEAGUE_CONFIG||{};const DEFAULTS=window.MALFA_DEFAULT_DATA||{};const STORAGE_KEY="malfa-demo-data-v2";const state={mode:"demo",client:null,competitions:[],clubs:[],entries:[],fixtures:[],standings:[],news:[],partners:[],settings:{},session:null};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])),num=v=>Number(v||0),clone=v=>JSON.parse(JSON.stringify(v)),uid=()=>crypto.randomUUID(),slugify=v=>String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
function cmsKey(){const c=window.MALFA_CMS||{};return c.supabasePublishableKey||c.supabaseAnonKey||""}function configured(){const c=window.MALFA_CMS||{};return Boolean(c.supabaseUrl&&cmsKey()&&window.supabase?.createClient)}function client(){state.client||=window.supabase.createClient(window.MALFA_CMS.supabaseUrl,cmsKey());return state.client}
function notice(msg,type="success"){const m=$("#adminNotice");m.textContent=msg;m.className=`admin-notice show ${type==="error"?"error":""}`;clearTimeout(notice.t);notice.t=setTimeout(()=>m.className="admin-notice",3600)}
function localData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||clone(DEFAULTS)}catch{return clone(DEFAULTS)}}function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify({competitions:state.competitions,clubs:state.clubs,entries:state.entries,fixtures:state.fixtures,standings:state.standings,news:state.news,partners:state.partners,settings:state.settings}))}
function comp(id){return state.competitions.find(c=>c.id===id)}function club(id){return state.clubs.find(c=>c.id===id)}function compName(id){return comp(id)?.short_name||id||"All"}function clubName(id){return club(id)?.name||"Club"}function localInput(v){if(!v)return"";const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}function fmt(v){return v?new Intl.DateTimeFormat("en-ZA",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"Date TBC"}
function optionList(items,selected="",blank=null,label="name"){return(blank!==null?`<option value="">${esc(blank)}</option>`:"")+items.map(x=>`<option value="${esc(x.id)}" ${x.id===selected?"selected":""}>${esc(x[label]||x.name)}</option>`).join("")}
async function imageValue(file,url,folder){if(file?.size){if(state.mode==="demo"){if(file.size>900000)throw new Error("Demo uploads must be smaller than 900 KB.");return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}const ext=file.name.split(".").pop().toLowerCase(),path=`${folder}/${uid()}.${ext}`,bucket=window.MALFA_CMS.storageBucket||"league-media";const{error}=await client().storage.from(bucket).upload(path,file,{cacheControl:"3600"});if(error)throw error;return client().storage.from(bucket).getPublicUrl(path).data.publicUrl}return String(url||"").trim()||null}
async function loadAll(){if(state.mode==="demo"){Object.assign(state,localData());renderAll();return}const [co,cl,en,fi,st,nw,pa]=await Promise.all([client().from("competitions").select("*").order("sort_order"),client().from("clubs").select("*").order("name"),client().from("competition_entries").select("*"),client().from("fixtures").select("*").order("kickoff_at",{ascending:false}),client().from("standings").select("*"),client().from("news_posts").select("*").order("created_at",{ascending:false}),client().from("partners").select("*").order("display_order")]);for(const r of[co,cl,en,fi,st,nw,pa])if(r.error)throw r.error;Object.assign(state,{competitions:co.data||[],clubs:cl.data||[],entries:en.data||[],fixtures:fi.data||[],standings:st.data||[],news:nw.data||[],partners:pa.data||[]});renderAll()}
async function init(){state.mode=configured()?"supabase":"demo";$("#adminMode").textContent=state.mode==="demo"?"Demo mode":"Live CMS";$("#adminTheme").addEventListener("click",()=>{const t=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=t;localStorage.setItem("malfa-theme",t)});bindTabs();bindForms();if(state.mode==="demo"){$("#dashboard").hidden=false;$("#adminIdentity").textContent="Local preview. Changes are saved in this browser only.";await loadAll();return}const{data}=await client().auth.getSession();await session(data.session);client().auth.onAuthStateChange((_e,s)=>session(s))}
async function session(s){state.session=s;if(!s){$("#loginPanel").hidden=false;$("#dashboard").hidden=true;return}$("#loginPanel").hidden=true;$("#dashboard").hidden=false;$("#logoutButton").hidden=false;$("#adminIdentity").textContent=`Signed in as ${s.user.email}`;await loadAll()}
function bindTabs(){$$('[data-tab]').forEach(b=>b.addEventListener("click",()=>{$$('[data-tab]').forEach(x=>x.classList.toggle("active",x===b));$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==b.dataset.tab)}))}
function bindForms(){$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const d=new FormData(e.currentTarget),{error}=await client().auth.signInWithPassword({email:d.get("email"),password:d.get("password")});if(error)notice(error.message,"error")});$("#logoutButton").addEventListener("click",()=>client().auth.signOut());
  $("#matchForm").addEventListener("submit",saveMatch);$("#resetMatch").addEventListener("click",resetMatch);$("#matchCompetitionFilter").addEventListener("change",renderMatches);$("#matchForm [name=competition_id]").addEventListener("change",renderMatchClubOptions);
  $("#tableCompetition").addEventListener("change",renderTable);$("#rebuildTable").addEventListener("click",()=>rebuildTable($("#tableCompetition").value,false));$("#saveTable").addEventListener("click",saveTable);
  $("#clubForm").addEventListener("submit",saveClub);$("#resetClub").addEventListener("click",resetClub);$("#clubForm [name=name]").addEventListener("input",e=>{const f=e.currentTarget.form;if(!f.elements.slug.dataset.touched)f.elements.slug.value=slugify(e.target.value)});$("#clubForm [name=slug]").addEventListener("input",e=>e.target.dataset.touched="1");
  $("#newsForm").addEventListener("submit",saveNews);$("#resetNews").addEventListener("click",resetNews);$("#newsForm [name=title]").addEventListener("input",e=>{const f=e.currentTarget.form;if(!f.elements.slug.dataset.touched)f.elements.slug.value=slugify(e.target.value)});$("#newsForm [name=slug]").addEventListener("input",e=>e.target.dataset.touched="1");
  $("#divisionForm").addEventListener("submit",e=>saveCompetition(e,"league"));$("#resetDivision").addEventListener("click",()=>resetCompetition("division"));$("#tournamentForm").addEventListener("submit",e=>saveCompetition(e,"tournament"));$("#resetTournament").addEventListener("click",()=>resetCompetition("tournament"));
  $("#partnerForm").addEventListener("submit",savePartner);$("#resetPartner").addEventListener("click",resetPartner)}
function renderAll(){populateSelects();renderMatches();renderTable();renderClubs();renderNews();renderCompetitions("league");renderCompetitions("tournament");renderPartners()}
function populateSelects(){const all=state.competitions.sort((a,b)=>num(a.sort_order)-num(b.sort_order)),leagues=all.filter(c=>c.type==="league");$("#matchForm [name=competition_id]").innerHTML=optionList(all);$("#matchCompetitionFilter").innerHTML=optionList(all,"","All competitions");$("#tableCompetition").innerHTML=optionList(leagues,$("#tableCompetition").value||leagues[0]?.id);$("#newsForm [name=competition_id]").innerHTML=optionList(all,$("#newsForm [name=competition_id]").value,"Association-wide");$("#newsForm [name=club_id]").innerHTML=optionList(state.clubs,$("#newsForm [name=club_id]").value,"No club");$("#clubCompetitionChecks").innerHTML=all.map(c=>`<label class="check-chip"><input type="checkbox" name="competition_ids" value="${esc(c.id)}"> ${esc(c.short_name)}</label>`).join("");renderMatchClubOptions()}
function renderMatchClubOptions(){const f=$("#matchForm"),cid=f.elements.competition_id.value,assigned=new Set(state.entries.filter(e=>e.competition_id===cid&&e.active!==false).map(e=>e.club_id)),clubs=assigned.size?state.clubs.filter(c=>assigned.has(c.id)):state.clubs;const h=f.elements.home_club_id.value,a=f.elements.away_club_id.value;f.elements.home_club_id.innerHTML=optionList(clubs,h,"Select home team");f.elements.away_club_id.innerHTML=optionList(clubs,a,"Select away team")}
async function saveEntity(table,payload,id=null){if(state.mode==="demo"){const key={competitions:"competitions",clubs:"clubs",fixtures:"fixtures",standings:"standings",news_posts:"news",partners:"partners"}[table];if(id){const i=state[key].findIndex(x=>x.id===id);if(i>=0)state[key][i]={...state[key][i],...payload,id}}else state[key].push({...payload,id:payload.id||uid()});saveLocal();return}const q=id?client().from(table).update(payload).eq("id",id):client().from(table).insert(payload);const{error}=await q;if(error)throw error}
async function deleteEntity(table,id){if(state.mode==="demo"){const key={competitions:"competitions",clubs:"clubs",fixtures:"fixtures",news_posts:"news",partners:"partners"}[table];state[key]=state[key].filter(x=>x.id!==id);if(table==="clubs"){state.entries=state.entries.filter(x=>x.club_id!==id);state.standings=state.standings.filter(x=>x.club_id!==id)}if(table==="competitions"){state.entries=state.entries.filter(x=>x.competition_id!==id);state.fixtures=state.fixtures.filter(x=>x.competition_id!==id);state.standings=state.standings.filter(x=>x.competition_id!==id)}saveLocal();return}const{error}=await client().from(table).delete().eq("id",id);if(error)throw error}
function renderMatches(){const id=$("#matchCompetitionFilter").value;const items=state.fixtures.filter(f=>!id||f.competition_id===id).sort((a,b)=>new Date(b.kickoff_at||0)-new Date(a.kickoff_at||0));$("#matchAdminList").innerHTML=items.map(f=>`<article class="admin-list-item"><span class="admin-thumb-placeholder">${esc(compName(f.competition_id))}</span><div><span class="badge">${esc(f.status)}${f.verified?" · verified":""}</span><h3>${esc(clubName(f.home_club_id))} ${f.status==="finished"?num(f.home_score):"vs"} ${f.status==="finished"?num(f.away_score):""} ${esc(clubName(f.away_club_id))}</h3><p>${esc(fmt(f.kickoff_at))} · ${esc(f.venue||"Venue TBC")}</p></div><div class="admin-actions"><button class="button secondary small" data-edit-match="${f.id}">Edit</button><button class="button danger small" data-delete-match="${f.id}">Delete</button></div></article>`).join("")||'<p class="muted">No matches yet.</p>';$$('[data-edit-match]').forEach(b=>b.onclick=()=>editMatch(b.dataset.editMatch));$$('[data-delete-match]').forEach(b=>b.onclick=()=>removeMatch(b.dataset.deleteMatch))}
function editMatch(id){const x=state.fixtures.find(f=>f.id===id),f=$("#matchForm");if(!x)return;["id","competition_id","home_club_id","away_club_id","venue","round_name","matchday","status","home_score","away_score","notes"].forEach(k=>f.elements[k].value=x[k]??"");f.elements.kickoff_at.value=localInput(x.kickoff_at);f.elements.verified.checked=!!x.verified;f.elements.featured.checked=!!x.featured;renderMatchClubOptions();f.scrollIntoView({behavior:"smooth"})}
function resetMatch(){$("#matchForm").reset();$("#matchForm [name=id]").value="";renderMatchClubOptions()}
async function saveMatch(e){e.preventDefault();const d=new FormData(e.currentTarget),id=d.get("id"),payload={competition_id:d.get("competition_id"),season:CONFIG.season,home_club_id:d.get("home_club_id"),away_club_id:d.get("away_club_id"),kickoff_at:d.get("kickoff_at")?new Date(d.get("kickoff_at")).toISOString():null,venue:String(d.get("venue")||"").trim()||null,round_name:String(d.get("round_name")||"").trim()||null,matchday:d.get("matchday")?num(d.get("matchday")):null,status:d.get("status"),home_score:d.get("home_score")===""?null:num(d.get("home_score")),away_score:d.get("away_score")===""?null:num(d.get("away_score")),verified:d.get("verified")==="on",featured:d.get("featured")==="on",notes:String(d.get("notes")||"").trim()||null,updated_at:new Date().toISOString()};if(payload.home_club_id===payload.away_club_id)return notice("Home and away teams must be different.","error");try{await saveEntity("fixtures",payload,id||null);await loadAll();if(comp(payload.competition_id)?.type==="league"&&payload.status==="finished"&&payload.verified)await rebuildTable(payload.competition_id,true);notice(id?"Match updated.":"Match added.");resetMatch();await loadAll()}catch(err){notice(err.message,"error")}}
async function removeMatch(id){if(!confirm("Delete this fixture or result?"))return;const old=state.fixtures.find(f=>f.id===id);try{await deleteEntity("fixtures",id);await loadAll();if(old&&comp(old.competition_id)?.type==="league")await rebuildTable(old.competition_id,true);notice("Match deleted.");await loadAll()}catch(err){notice(err.message,"error")}}
function tableRows(cid,fromResults=false){const ids=new Set(state.entries.filter(e=>e.competition_id===cid&&e.active!==false).map(e=>e.club_id));let rows=state.standings.filter(r=>r.competition_id===cid);state.clubs.filter(c=>ids.has(c.id)).forEach(c=>{if(!rows.some(r=>r.club_id===c.id))rows.push({id:uid(),competition_id:cid,season:CONFIG.season,club_id:c.id,won:0,drawn:0,lost:0,goals_for:0,goals_against:0,points_adjustment:0})});if(fromResults){const adjustments=Object.fromEntries(rows.map(r=>[r.club_id,num(r.points_adjustment)]));rows=state.clubs.filter(c=>ids.has(c.id)).map(c=>({id:rows.find(r=>r.club_id===c.id)?.id||uid(),competition_id:cid,season:CONFIG.season,club_id:c.id,won:0,drawn:0,lost:0,goals_for:0,goals_against:0,points_adjustment:adjustments[c.id]||0}));const map=Object.fromEntries(rows.map(r=>[r.club_id,r]));state.fixtures.filter(f=>f.competition_id===cid&&f.status==="finished"&&f.verified&&Number.isFinite(Number(f.home_score))&&Number.isFinite(Number(f.away_score))).forEach(f=>{const h=map[f.home_club_id],a=map[f.away_club_id];if(!h||!a)return;h.goals_for+=num(f.home_score);h.goals_against+=num(f.away_score);a.goals_for+=num(f.away_score);a.goals_against+=num(f.home_score);if(num(f.home_score)>num(f.away_score)){h.won++;a.lost++}else if(num(f.home_score)<num(f.away_score)){a.won++;h.lost++}else{h.drawn++;a.drawn++}})}return sortRows(rows)}
function sortRows(rows){return rows.map(r=>({...r,played:num(r.won)+num(r.drawn)+num(r.lost),goal_difference:num(r.goals_for)-num(r.goals_against),points:num(r.won)*3+num(r.drawn)+num(r.points_adjustment)})).sort((a,b)=>num(b.points)-num(a.points)||num(b.goal_difference)-num(a.goal_difference)||num(b.goals_for)-num(a.goals_for)||num(b.won)-num(a.won)||(clubName(a.club_id)).localeCompare(clubName(b.club_id))).map((r,i)=>({...r,position:i+1}))}
function renderTable(rows=null){const cid=$("#tableCompetition").value;if(!cid)return;rows=rows||tableRows(cid);$("#tableEditorBody").innerHTML=rows.map(r=>`<tr data-row="${r.club_id}"><td data-pos>${r.position}</td><td><strong>${esc(clubName(r.club_id))}</strong></td><td data-played>${r.played}</td>${["won","drawn","lost","goals_for","goals_against"].map(k=>`<td><input class="table-input" name="${k}" type="number" min="0" value="${num(r[k])}"></td>`).join("")}<td data-gd>${r.goal_difference}</td><td><input class="table-input adjustment" name="points_adjustment" type="number" value="${num(r.points_adjustment)}"></td><td data-points>${r.points}</td></tr>`).join("")||'<tr><td colspan="11">Assign clubs to this division first.</td></tr>';$$('[data-row] input').forEach(i=>i.oninput=()=>recalcEditor())}
function readEditor(){const cid=$("#tableCompetition").value;return $$('[data-row]').map(tr=>({id:state.standings.find(r=>r.competition_id===cid&&r.club_id===tr.dataset.row)?.id||uid(),competition_id:cid,season:CONFIG.season,club_id:tr.dataset.row,won:num($("[name=won]",tr).value),drawn:num($("[name=drawn]",tr).value),lost:num($("[name=lost]",tr).value),goals_for:num($("[name=goals_for]",tr).value),goals_against:num($("[name=goals_against]",tr).value),points_adjustment:num($("[name=points_adjustment]",tr).value)}))}
function recalcEditor(){renderTable(sortRows(readEditor()))}
async function persistTable(rows){if(state.mode==="demo"){const cid=rows[0]?.competition_id;state.standings=state.standings.filter(r=>r.competition_id!==cid).concat(rows);saveLocal();return}const payload=rows.map(({id,...r})=>({...r,updated_at:new Date().toISOString()}));const{error}=await client().from("standings").upsert(payload,{onConflict:"competition_id,season,club_id"});if(error)throw error}
async function rebuildTable(cid,silent=false){const rows=tableRows(cid,true);try{await persistTable(rows);if(!silent){renderTable(rows);notice("Table rebuilt from verified results.")}}catch(err){notice(err.message,"error")}}
async function saveTable(){const rows=sortRows(readEditor());if(!rows.length)return notice("Assign clubs before saving the table.","error");try{await persistTable(rows);renderTable(rows);notice("Table calculated and published.");await loadAll()}catch(err){notice(err.message,"error")}}
function renderClubs(){$("#clubAdminList").innerHTML=state.clubs.map(c=>`<article class="admin-list-item">${c.crest_url?`<img src="${esc(c.crest_url)}" alt="">`:`<span class="admin-thumb-placeholder">${esc(c.short_name||"CLB")}</span>`}<div><span class="badge">${c.active?"Active":"Hidden"}</span><h3>${esc(c.name)}</h3><p>${esc(c.ground||c.location||"Details TBC")}</p></div><div class="admin-actions"><button class="button secondary small" data-edit-club="${c.id}">Edit</button><button class="button danger small" data-delete-club="${c.id}">Delete</button></div></article>`).join("")||'<p class="muted">No clubs yet.</p>';$$('[data-edit-club]').forEach(b=>b.onclick=()=>editClub(b.dataset.editClub));$$('[data-delete-club]').forEach(b=>b.onclick=()=>removeClub(b.dataset.deleteClub))}
function editClub(id){const x=club(id),f=$("#clubForm");["id","name","short_name","slug","founded_year","location","ground","description","crest_url","website","instagram"].forEach(k=>f.elements[k].value=x[k]??"");f.elements.active.checked=x.active!==false;const ids=new Set(state.entries.filter(e=>e.club_id===id&&e.active!==false).map(e=>e.competition_id));$$('[name=competition_ids]',f).forEach(i=>i.checked=ids.has(i.value));f.elements.slug.dataset.touched="1";f.scrollIntoView({behavior:"smooth"})}
function resetClub(){$("#clubForm").reset();$("#clubForm [name=id]").value="";$("#clubForm [name=active]").checked=true;$("#clubForm [name=slug]").dataset.touched=""}
async function syncEntries(clubId,ids){if(state.mode==="demo"){state.entries=state.entries.filter(e=>e.club_id!==clubId).concat(ids.map(cid=>({id:uid(),club_id:clubId,competition_id:cid,season:CONFIG.season,active:true})));saveLocal();return}let{error}=await client().from("competition_entries").delete().eq("club_id",clubId);if(error)throw error;if(ids.length){({error}=await client().from("competition_entries").insert(ids.map(cid=>({club_id:clubId,competition_id:cid,season:CONFIG.season,active:true}))));if(error)throw error}}
async function saveClub(e){e.preventDefault();const d=new FormData(e.currentTarget),id=d.get("id")||uid();try{const crest=await imageValue(d.get("crest_file"),d.get("crest_url"),"crests"),payload={slug:slugify(d.get("slug")),name:String(d.get("name")).trim(),short_name:String(d.get("short_name")||"").trim()||null,crest_url:crest,location:String(d.get("location")||"").trim()||null,ground:String(d.get("ground")||"").trim()||null,founded_year:d.get("founded_year")?num(d.get("founded_year")):null,description:String(d.get("description")||"").trim()||null,website:String(d.get("website")||"").trim()||null,instagram:String(d.get("instagram")||"").trim()||null,active:d.get("active")==="on",updated_at:new Date().toISOString()};await saveEntity("clubs",payload,d.get("id")||null);const actualId=d.get("id")|| (state.mode==="demo"?state.clubs[state.clubs.length-1].id:(await client().from("clubs").select("id").eq("slug",payload.slug).single()).data.id);await syncEntries(actualId,d.getAll("competition_ids"));notice(d.get("id")?"Club updated, including crest.":"Club added.");resetClub();await loadAll()}catch(err){notice(err.message,"error")}}
async function removeClub(id){if(!confirm("Delete this club and its competition entries?"))return;try{await deleteEntity("clubs",id);notice("Club deleted.");await loadAll()}catch(err){notice(err.message,"error")}}
function renderNews(){$("#newsAdminList").innerHTML=state.news.map(n=>`<article class="admin-list-item">${n.image_url?`<img src="${esc(n.image_url)}" alt="">`:'<span class="admin-thumb-placeholder">NEWS</span>'}<div><span class="badge">${n.published?"Published":"Draft"} · ${esc(compName(n.competition_id))}</span><h3>${esc(n.title)}</h3><p>${esc(n.category||"Football News")}</p></div><div class="admin-actions"><button class="button secondary small" data-edit-news="${n.id}">Edit</button><button class="button danger small" data-delete-news="${n.id}">Delete</button></div></article>`).join("")||'<p class="muted">No news yet.</p>';$$('[data-edit-news]').forEach(b=>b.onclick=()=>editNews(b.dataset.editNews));$$('[data-delete-news]').forEach(b=>b.onclick=()=>removeNews(b.dataset.deleteNews))}
function editNews(id){const x=state.news.find(n=>n.id===id),f=$("#newsForm");["id","title","slug","category","competition_id","club_id","excerpt","body","image_url"].forEach(k=>f.elements[k].value=x[k]??"");f.elements.published.checked=!!x.published;f.elements.slug.dataset.touched="1";f.scrollIntoView({behavior:"smooth"})}
function resetNews(){$("#newsForm").reset();$("#newsForm [name=id]").value="";$("#newsForm [name=category]").value="Football News";$("#newsForm [name=slug]").dataset.touched=""}
async function saveNews(e){e.preventDefault();const d=new FormData(e.currentTarget),id=d.get("id");try{const image=await imageValue(d.get("image_file"),d.get("image_url"),"news"),published=d.get("published")==="on",payload={title:String(d.get("title")).trim(),slug:slugify(d.get("slug")),category:String(d.get("category")||"Football News").trim(),competition_id:d.get("competition_id")||null,club_id:d.get("club_id")||null,excerpt:String(d.get("excerpt")||"").trim()||null,body:String(d.get("body")||"").trim()||null,image_url:image,published,published_at:published?new Date().toISOString():null,updated_at:new Date().toISOString()};await saveEntity("news_posts",payload,id||null);notice(id?"News updated.":"News added.");resetNews();await loadAll()}catch(err){notice(err.message,"error")}}
async function removeNews(id){if(!confirm("Delete this story?"))return;try{await deleteEntity("news_posts",id);notice("News deleted.");await loadAll()}catch(err){notice(err.message,"error")}}
function renderCompetitions(type){const mount=type==="league"?$("#divisionAdminList"):$("#tournamentAdminList");mount.innerHTML=state.competitions.filter(c=>c.type===type).sort((a,b)=>num(a.sort_order)-num(b.sort_order)).map(c=>`<article class="admin-list-item"><span class="admin-thumb-placeholder">${esc(c.short_name)}</span><div><span class="badge">${c.visible?"Public":"Hidden"} · ${c.active?"Active":"Inactive"}</span><h3>${esc(c.name)}</h3><p>${esc(c.category||type)}</p></div><div class="admin-actions"><button class="button secondary small" data-edit-comp="${c.id}" data-type="${type}">Edit</button><button class="button danger small" data-delete-comp="${c.id}">Delete</button></div></article>`).join("")||'<p class="muted">No competitions yet.</p>';$$('[data-edit-comp]',mount).forEach(b=>b.onclick=()=>editCompetition(b.dataset.editComp,b.dataset.type));$$('[data-delete-comp]',mount).forEach(b=>b.onclick=()=>removeCompetition(b.dataset.deleteComp))}
function editCompetition(id,type){const x=comp(id),f=$(type==="league"?"#divisionForm":"#tournamentForm");f.elements.original_id.value=x.id;["id","name","short_name","category","sort_order","accent","description"].forEach(k=>f.elements[k].value=x[k]??"");f.elements.visible.checked=x.visible!==false;f.elements.active.checked=x.active!==false;f.scrollIntoView({behavior:"smooth"})}
function resetCompetition(type){const f=$(type==="division"?"#divisionForm":"#tournamentForm");f.reset();f.elements.original_id.value="";f.elements.sort_order.value=type==="division"?100:200;f.elements.accent.value="#d8202f";f.elements.active.checked=true;f.elements.visible.checked=type==="division"}
async function saveCompetition(e,type){e.preventDefault();const d=new FormData(e.currentTarget),original=d.get("original_id"),id=slugify(d.get("id")),payload={id,slug:id,name:String(d.get("name")).trim(),short_name:String(d.get("short_name")).trim(),category:String(d.get("category")||"").trim(),type,description:String(d.get("description")||"").trim()||null,accent:d.get("accent")||"#d8202f",sort_order:num(d.get("sort_order")),visible:d.get("visible")==="on",active:d.get("active")==="on",updated_at:new Date().toISOString()};if(original&&original!==id)return notice("Competition IDs cannot be changed after creation. Create a new competition instead.","error");try{await saveEntity("competitions",payload,original||null);notice(`${type==="league"?"Division":"Tournament"} saved.`);resetCompetition(type==="league"?"division":"tournament");await loadAll()}catch(err){notice(err.message,"error")}}
async function removeCompetition(id){if(!confirm("Delete this competition and related entries?"))return;try{await deleteEntity("competitions",id);notice("Competition deleted.");await loadAll()}catch(err){notice(err.message,"error")}}
function renderPartners(){$("#partnerAdminList").innerHTML=state.partners.map(p=>`<article class="admin-list-item">${p.logo_url?`<img src="${esc(p.logo_url)}" alt="">`:'<span class="admin-thumb-placeholder">PART</span>'}<div><span class="badge">${esc(p.tier||"Partner")} · ${p.active?"Public":"Hidden"}</span><h3>${esc(p.name)}</h3><p>${esc(p.website||"")}</p></div><div class="admin-actions"><button class="button secondary small" data-edit-partner="${p.id}">Edit</button><button class="button danger small" data-delete-partner="${p.id}">Delete</button></div></article>`).join("")||'<p class="muted">No partners yet.</p>';$$('[data-edit-partner]').forEach(b=>b.onclick=()=>editPartner(b.dataset.editPartner));$$('[data-delete-partner]').forEach(b=>b.onclick=()=>removePartner(b.dataset.deletePartner))}
function editPartner(id){const x=state.partners.find(p=>p.id===id),f=$("#partnerForm");["id","name","tier","display_order","logo_url","website","description"].forEach(k=>f.elements[k].value=x[k]??"");f.elements.active.checked=x.active!==false;f.scrollIntoView({behavior:"smooth"})}
function resetPartner(){$("#partnerForm").reset();$("#partnerForm [name=id]").value="";$("#partnerForm [name=active]").checked=true}
async function savePartner(e){e.preventDefault();const d=new FormData(e.currentTarget),id=d.get("id");try{const logo=await imageValue(d.get("logo_file"),d.get("logo_url"),"partners"),payload={name:String(d.get("name")).trim(),tier:d.get("tier"),display_order:num(d.get("display_order")),logo_url:logo,website:String(d.get("website")||"").trim()||null,description:String(d.get("description")||"").trim()||null,active:d.get("active")==="on",updated_at:new Date().toISOString()};await saveEntity("partners",payload,id||null);notice(id?"Partner updated.":"Partner added.");resetPartner();await loadAll()}catch(err){notice(err.message,"error")}}
async function removePartner(id){if(!confirm("Delete this partner?"))return;try{await deleteEntity("partners",id);notice("Partner deleted.");await loadAll()}catch(err){notice(err.message,"error")}}
document.addEventListener("DOMContentLoaded",init);
