const CONFIG = window.LEAGUE_CONFIG || {};
const DEFAULTS = window.MALFA_DEFAULT_DATA || {};
const PAGE = document.body?.dataset?.page || "home";
const STORAGE_KEY = "malfa-demo-data-v2";
const state = { competition: new URLSearchParams(location.search).get("competition") || "all", competitions:[], clubs:[], entries:[], fixtures:[], standings:[], news:[], partners:[], settings:{}, client:null };
const $ = (s,r=document)=>r.querySelector(s);
const $$ = (s,r=document)=>[...r.querySelectorAll(s)];
const esc = (v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const attr=esc;
const num=v=>Number(v||0);
const slug=v=>String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const clone=v=>JSON.parse(JSON.stringify(v));
const dateAsc=(a,b)=>new Date(a.kickoff_at||0)-new Date(b.kickoff_at||0);
const dateDesc=(a,b)=>new Date(b.kickoff_at||0)-new Date(a.kickoff_at||0);
function cmsKey(){const c=window.MALFA_CMS||{};return c.supabasePublishableKey||c.supabaseAnonKey||""}function configured(){const c=window.MALFA_CMS||{};return Boolean(c.supabaseUrl&&cmsKey()&&window.supabase?.createClient)}
function client(){if(!configured())return null;state.client||=window.supabase.createClient(window.MALFA_CMS.supabaseUrl,cmsKey());return state.client}
function localData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||clone(DEFAULTS)}catch{return clone(DEFAULTS)}}
function competition(id){return state.competitions.find(c=>c.id===id)}
function publicCompetitions(type){return state.competitions.filter(c=>c.active!==false&&c.visible!==false&&(!type||c.type===type)).sort((a,b)=>num(a.sort_order)-num(b.sort_order))}
function competitionLabel(id){return competition(id)?.short_name||String(id||"").toUpperCase()||"All"}
function club(id){return state.clubs.find(c=>c.id===id)||{name:"TBC",short_name:"TBC"}}
function clubMark(item,compact=false){const cls=compact?" compact":"";return item?.crest_url?`<span class="club-mark${cls}"><img src="${attr(item.crest_url)}" alt="${attr(item.name||"Club")} crest"></span>`:`<span class="club-mark${cls}">${esc(item?.short_name||initials(item?.name))}</span>`}
function initials(name="Club"){return name.split(/\s+/).slice(0,3).map(x=>x[0]).join("").toUpperCase()}
function fmtDate(v,opts={day:"numeric",month:"short",year:"numeric"}){if(!v)return"Date TBC";return new Intl.DateTimeFormat("en-ZA",opts).format(new Date(v))}
function fmtTime(v){if(!v)return"Time TBC";return new Intl.DateTimeFormat("en-ZA",{hour:"2-digit",minute:"2-digit"}).format(new Date(v))}
function statusLabel(v){return({scheduled:"Scheduled",live:"Live",finished:"Full time",postponed:"Postponed",cancelled:"Cancelled"})[v]||"Scheduled"}
function empty(title,copy,code="MALFA"){return`<div class="empty-state"><strong>${esc(code)}</strong><h3>${esc(title)}</h3><p>${esc(copy)}</p></div>`}
function updateQuery(value){const u=new URL(location.href);value==="all"?u.searchParams.delete("competition"):u.searchParams.set("competition",value);history.replaceState({},"",u)}
function competitionHref(value){const u=new URL(location.href);value==="all"?u.searchParams.delete("competition"):u.searchParams.set("competition",value);return `${u.pathname.split("/").pop()||"index.html"}${u.search}${u.hash}`}
function entriesForClub(id){return state.entries.filter(e=>e.club_id===id&&e.active!==false).map(e=>e.competition_id)}
function clubsForCompetition(id){const ids=new Set(state.entries.filter(e=>e.competition_id===id&&e.active!==false).map(e=>e.club_id));return state.clubs.filter(c=>ids.has(c.id)&&c.active!==false)}

async function loadData(){
  const local=localData(); Object.assign(state,{competitions:local.competitions||[],clubs:local.clubs||[],entries:local.entries||[],fixtures:local.fixtures||[],standings:local.standings||[],news:local.news||[],partners:local.partners||[],settings:local.settings||{}});
  const db=client(); if(!db)return;
  const [co,cl,en,fi,st,nw,pa,se]=await Promise.all([
    db.from("competitions").select("*").eq("active",true).order("sort_order"),
    db.from("clubs").select("*").eq("active",true).order("name"),
    db.from("competition_entries").select("*").eq("active",true),
    db.from("fixtures").select("*").order("kickoff_at"),
    db.from("standings").select("*"),
    db.from("news_posts").select("*").eq("published",true).order("published_at",{ascending:false}),
    db.from("partners").select("*").eq("active",true).order("display_order"),
    db.from("site_settings").select("key,value")
  ]);
  if(!co.error)state.competitions=co.data||[]; if(!cl.error)state.clubs=cl.data||[]; if(!en.error)state.entries=en.data||[]; if(!fi.error)state.fixtures=fi.data||[]; if(!st.error)state.standings=st.data||[]; if(!nw.error)state.news=nw.data||[]; if(!pa.error)state.partners=pa.data||[]; if(!se.error)state.settings=Object.fromEntries((se.data||[]).map(x=>[x.key,x.value]));
}

function navItems(){return[["Home","index.html","home"],["Results","matches.html","matches"],["Fixtures","fixtures.html","fixtures"],["Tables","standings.html","standings"],["Clubs","clubs.html","clubs"],["News","news.html","news"],["Tournaments","tournaments.html","tournaments"],["Partners","partners.html","partners"]]}
function renderHeader(){const m=$("[data-site-header]");if(!m)return;const links=navItems().map(([l,h,k])=>`<a class="nav-link ${PAGE===k?"active":""}" href="${h}">${l}</a>`).join("");m.innerHTML=`<a class="skip-link" href="#main">Skip to content</a><div class="topline"><div class="container topline-inner"><span>${esc(CONFIG.season)} competition centre</span><span>${esc(CONFIG.strapline)}</span><a href="admin.html">Admin</a></div></div><header class="site-header"><div class="container nav-wrap"><a class="brand" href="index.html"><img src="${attr(CONFIG.logo)}" alt="MALFA crest"><span class="brand-text">MALFA<small>Mamelodi Local Football Association</small></span></a><nav class="desktop-nav" aria-label="Main navigation">${links}</nav><div class="header-actions"><button class="icon-button theme-toggle" type="button" aria-label="Toggle dark mode">◐</button><button class="icon-button menu-button" type="button" aria-label="Open menu">☰</button></div></div></header><div class="mobile-menu"><nav>${links}</nav></div>`;
  const menu=$(".menu-button"),panel=$(".mobile-menu");menu?.addEventListener("click",()=>{panel.classList.toggle("open");document.body.classList.toggle("menu-open",panel.classList.contains("open"));menu.textContent=panel.classList.contains("open")?"×":"☰"});
  $(".theme-toggle")?.addEventListener("click",toggleTheme);
}
function toggleTheme(){const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("malfa-theme",next)}
function renderFooter(){const m=$("[data-site-footer]");if(!m)return;m.innerHTML=`<footer class="site-footer"><div class="container footer-grid"><div class="footer-brand"><img src="${attr(CONFIG.logo)}" alt="MALFA crest"><p>MALFA competition information across junior, senior, women’s and tournament football.</p></div><div><p class="footer-title">Competition</p><div class="footer-links"><a href="matches.html">Results</a><a href="fixtures.html">Fixtures</a><a href="standings.html">Tables</a><a href="tournaments.html">Tournaments</a></div></div><div><p class="footer-title">Community</p><div class="footer-links"><a href="clubs.html">Clubs</a><a href="news.html">News</a><a href="partners.html">Partners</a><a href="about.html">About</a></div></div><div><p class="footer-title">Association</p><div class="footer-links"><a href="contact.html">Contact</a><a href="admin.html">Admin dashboard</a></div></div></div><div class="footer-bottom"><div class="container">© ${new Date().getFullYear()} Mamelodi Local Football Association. Competition data is published by authorised administrators.</div></div></footer>`}

const DIVISION_FAMILIES=[
  {id:"u11",label:"U11",order:10,match:c=>String(c.id||"").startsWith("u11")},
  {id:"u13",label:"U13",order:20,match:c=>String(c.id||"").startsWith("u13")},
  {id:"u15",label:"U15",order:30,match:c=>String(c.id||"").startsWith("u15")},
  {id:"u17",label:"U17",order:40,match:c=>String(c.id||"").startsWith("u17")},
  {id:"u19",label:"U19",order:50,match:c=>String(c.id||"").startsWith("u19")},
  {id:"mpl",label:"MPL",order:60,match:c=>String(c.id||"")==="mpl"||String(c.id||"").startsWith("mpl-")},
  {id:"super",label:"SUPER",order:70,match:c=>String(c.id||"").startsWith("super")},
  {id:"wpl",label:"WPL",order:80,match:c=>String(c.id||"")==="wpl"||/women|wpl/i.test(`${c.name||""} ${c.short_name||""}`)},
  {id:"cups",label:"CUPS",order:90,match:c=>c.type==="tournament"}
];
function competitionFamily(c){if(!c)return null;return DIVISION_FAMILIES.find(f=>f.match(c))?.id||`other:${c.id}`}
function competitionGroups(comps){const groups=new Map();comps.forEach(c=>{const id=competitionFamily(c),known=DIVISION_FAMILIES.find(f=>f.id===id);if(!groups.has(id))groups.set(id,{id,label:known?.label||c.category||c.short_name||c.name,order:known?.order??1000,competitions:[]});groups.get(id).competitions.push(c)});return[...groups.values()].map(g=>({...g,competitions:g.competitions.sort((a,b)=>num(a.sort_order)-num(b.sort_order))})).sort((a,b)=>a.order-b.order||String(a.label).localeCompare(String(b.label)))}
function streamLabel(c,family,total){let label=String(c.short_name||c.name||"").trim();const prefixes={u11:/^U11\s*/i,u13:/^U13\s*/i,u15:/^U15\s*/i,u17:/^U17\s*/i,u19:/^U19\s*/i,mpl:/^MPL\s*/i,super:/^SUPER(?:\s+LEAGUE)?\s*/i,wpl:/^(?:MALFA\s+)?(?:WOMEN(?:'S)?\s+PROMOTIONAL\s+LEAGUE|WPL)\s*/i};label=label.replace(prefixes[family]||/^$/,"").replace(/^[-–—:\s]+/,"").trim();if(family==="super"&&/^[AB]$/i.test(label))label=`Stream ${label.toUpperCase()}`;if(!label)label=total>1?c.name:"League";return label}
function filterButtons(mount,includeAll=true,type=null){if(!mount)return;const comps=publicCompetitions(type),groups=competitionGroups(comps),selected=competition(state.competition),activeFamily=selected?competitionFamily(selected):(state.competition==="all"?"all":groups[0]?.id),activeGroup=groups.find(g=>g.id===activeFamily);mount.classList.add("competition-filter-mount");const divisionLinks=(includeAll?`<a class="division-filter ${state.competition==="all"?"active":""}" href="${attr(competitionHref("all"))}" ${state.competition==="all"?'aria-current="page"':""}>All competitions</a>`:"")+groups.map(g=>{const first=g.competitions[0];return`<a class="division-filter ${activeFamily===g.id?"active":""}" href="${attr(competitionHref(first.id))}" ${activeFamily===g.id?'aria-current="true"':""}>${esc(g.label)}</a>`}).join("");const streamLinks=activeGroup?`<div class="stream-filter-row" aria-label="${esc(activeGroup.label)} competitions"><span class="stream-filter-label">Choose ${activeGroup.label} competition</span><div class="stream-filter-options">${activeGroup.competitions.map(c=>`<a class="stream-filter ${state.competition===c.id?"active":""}" href="${attr(competitionHref(c.id))}" ${state.competition===c.id?'aria-current="page"':""}>${esc(streamLabel(c,activeGroup.id,activeGroup.competitions.length))}</a>`).join("")}</div></div>`:"";mount.innerHTML=`<div class="competition-filter"><div class="division-filter-row" aria-label="Divisions">${divisionLinks}</div>${streamLinks}</div>`}
function filteredFixtures(){return state.fixtures.filter(f=>state.competition==="all"||f.competition_id===state.competition).filter(f=>competition(f.competition_id)?.visible!==false)}
function matchCard(f){const h=club(f.home_club_id),a=club(f.away_club_id),score=f.status==="finished"||f.status==="live";return`<article class="match-card"><div class="match-date"><strong>${esc(fmtDate(f.kickoff_at,{day:"numeric",month:"short"}))}</strong><span>${esc(fmtTime(f.kickoff_at))}</span><span class="status ${f.status==="live"?"live":""}">${esc(statusLabel(f.status))}</span></div><div class="match-card-teams"><div class="match-card-team">${clubMark(h,true)}<strong>${esc(h.name)}</strong><span class="team-score">${score?num(f.home_score):"–"}</span></div><div class="match-card-team">${clubMark(a,true)}<strong>${esc(a.name)}</strong><span class="team-score">${score?num(f.away_score):"–"}</span></div></div><div class="match-card-meta"><strong>${esc(competitionLabel(f.competition_id))}${f.round_name?` · ${esc(f.round_name)}`:""}</strong><span>${esc(f.venue||"Venue TBC")}</span>${f.verified?'<span class="status verified">Verified</span>':""}</div></article>`}
function sortStandings(rows){return [...rows].map(r=>({...r,played:num(r.won)+num(r.drawn)+num(r.lost),goal_difference:num(r.goals_for)-num(r.goals_against),points:num(r.won)*3+num(r.drawn)+num(r.points_adjustment)})).sort((a,b)=>num(b.points)-num(a.points)||num(b.goal_difference)-num(a.goal_difference)||num(b.goals_for)-num(a.goals_for)||num(b.won)-num(a.won)||(club(a.club_id).name||"").localeCompare(club(b.club_id).name||"")).map((r,i)=>({...r,position:i+1}))}
const CHAMPIONSHIP_FAMILIES=new Set(["u11","u13","u15","u19","mpl","super"]);
function competitionMovement(c){const family=competitionFamily(c);return{family,playoff:CHAMPIONSHIP_FAMILIES.has(family),relegation:family==="super",promotion:family==="u19"||family==="mpl"}}
function positionRule(c,index,total){const rule=competitionMovement(c);if(rule.relegation&&index===total-1)return{className:"relegation",label:"Relegation position"};if(rule.playoff&&index===0)return{className:"playoff",label:rule.promotion?"Championship playoff qualifier · champion promoted to Super League":"Championship playoff qualifier"};return{className:"",label:""}}
function ruleSummary(c){const family=competitionFamily(c);if(["u11","u13","u15"].includes(family))return"Only first-place clubs enter the championship pathway. The East streams produce one East representative, the West streams produce one West representative, and those representatives meet for the division title. Runners-up do not qualify.";if(family==="u19")return"The East and West first-place clubs meet in the final playoff. The winner is U19 champion and earns one promotion place in the Super League.";if(family==="mpl")return"The East and West first-place clubs meet in the final playoff. The winner is MPL champion and earns one promotion place in the Super League.";if(family==="super")return"The Stream A and Stream B first-place clubs meet in the final playoff, with the winner crowned Super League champion. The bottom club in each stream is relegated, giving two relegation places in total. Those places are filled by the U19 champion and the MPL champion.";return""}
function standingsLegend(c){const rule=competitionMovement(c),items=[];if(rule.playoff)items.push('<span><i class="legend-marker playoff"></i>Championship playoff qualifier</span>');if(rule.relegation)items.push('<span><i class="legend-marker relegation"></i>Relegation position</span>');return items.length?`<div class="table-legend" aria-label="Table position key">${items.join("")}</div>`:""}
function standingsTable(rows,compact=false){const sorted=sortStandings(rows);if(!sorted.length)return empty("No table published","The table will appear after clubs and results are added.","TABLE");const c=competition(sorted[0]?.competition_id),summary=ruleSummary(c);return`<div class="table-shell"><table class="league-table"><thead><tr><th>#</th><th>Club</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>Pts</th></tr></thead><tbody>${sorted.map((r,i)=>{const team=club(r.club_id),mark=positionRule(c,i,sorted.length);return`<tr class="${mark.className?`position-${mark.className}`:""}"><td><span class="position-marker ${mark.className}" title="${attr(mark.label)}"></span>${i+1}${mark.label?`<span class="sr-only"> · ${esc(mark.label)}</span>`:""}</td><td><div class="table-team">${clubMark(team,true)}<strong>${esc(team.name)}</strong></div></td><td>${r.played}</td><td>${num(r.won)}</td><td>${num(r.drawn)}</td><td>${num(r.lost)}</td><td>${num(r.goals_for)}</td><td>${num(r.goals_against)}</td><td>${r.goal_difference>0?"+":""}${r.goal_difference}</td><td class="points">${r.points}</td></tr>`}).join("")}</tbody></table></div>${compact?"":standingsLegend(c)}<p class="table-note">Ranking order: points, goal difference, goals scored, wins, then club name.${!compact&&summary?` <strong>Competition rule:</strong> ${esc(summary)}`:""}</p>`}
function leaderForCompetition(c){const rows=sortStandings(state.standings.filter(r=>r.competition_id===c.id));if(!rows.length)return{label:"Table not published",club:null};const started=rows.some(r=>num(r.played)>0||num(r.points)!==0||num(r.goals_for)!==0||num(r.goals_against)!==0);return started?{label:club(rows[0].club_id).name,club:club(rows[0].club_id)}:{label:"Competition not started",club:null}}
function playoffPathway(c){const family=competitionFamily(c);if(!CHAMPIONSHIP_FAMILIES.has(family))return"";const group=competitionGroups(publicCompetitions("league")).find(g=>g.id===family);if(!group)return"";const leaders=group.competitions.map(stream=>({stream,label:streamLabel(stream,family,group.competitions.length),leader:leaderForCompetition(stream)}));const finalText=["u11","u13","u15"].includes(family)?"East representative vs West representative":family==="super"?"Stream A winner vs Stream B winner":"East winner vs West winner";const outcome=family==="u19"?"Champion promoted to Super League":family==="mpl"?"Champion promoted to Super League":family==="super"?"Winner crowned Super League champion · two relegated · U19 and MPL champions promoted":"Winner crowned division champion";return`<aside class="playoff-pathway" aria-label="${esc(group.label)} championship pathway"><div class="playoff-pathway-head"><div><span class="eyebrow">Championship pathway</span><h3>${esc(group.label)} playoff</h3></div><span class="status">1st place only</span></div><div class="playoff-qualifier-grid">${leaders.map(x=>`<a class="playoff-qualifier" href="standings.html?competition=${encodeURIComponent(x.stream.id)}"><small>${esc(x.label)}</small><strong>${x.leader.club?esc(x.leader.club.name):esc(x.leader.label)}</strong><span>${x.leader.club?"Current first place":"Awaiting table"}</span></a>`).join("")}</div><div class="playoff-final-line"><span>${esc(finalText)}</span><strong>${esc(outcome)}</strong></div><p>${esc(ruleSummary(c))}</p></aside>`}
function divisionCard(c){return`<a class="division-card" style="--accent:${attr(c.accent||"#d8202f")}" href="standings.html?competition=${encodeURIComponent(c.id)}"><div class="division-short">${esc(c.short_name)}</div><h3>${esc(c.name)}</h3><p>${esc(c.description||"")}</p><footer>→</footer></a>`}
function clubCard(c){const comps=entriesForClub(c.id).map(id=>competition(id)).filter(x=>x&&x.visible!==false);return`<article class="club-card">${clubMark(c)}<h3>${esc(c.name)}</h3><p>${esc(c.location||c.ground||"Club details to be confirmed")}</p><div class="mini-pills">${comps.map(x=>`<span class="mini-pill">${esc(x.short_name)}</span>`).join("")}</div><a class="text-link" href="club.html?id=${encodeURIComponent(c.slug||c.id)}">Club profile →</a></article>`}
function newsCard(n){return`<article class="card news-card">${n.image_url?`<img src="${attr(n.image_url)}" alt="">`:'<div class="news-image-placeholder">MALFA</div>'}<div class="card-body"><div class="news-meta"><span>${esc(n.category||"Football News")}</span><span>${esc(fmtDate(n.published_at))}</span></div><h3>${esc(n.title)}</h3><p>${esc(n.excerpt||"")}</p><a class="text-link" href="article.html?id=${encodeURIComponent(n.slug||n.id)}">Read story →</a></div></article>`}
function partnerCard(p){return`<a class="partner-card" href="${attr(p.website||"#")}" ${p.website?'target="_blank" rel="noopener"':""}><div class="partner-logo">${p.logo_url?`<img src="${attr(p.logo_url)}" alt="${attr(p.name)} logo">`:`<span class="partner-logo-placeholder">${esc(initials(p.name))}</span>`}</div><div><small>${esc(p.tier||"Partner")}</small><h3>${esc(p.name)}</h3></div></a>`}

function renderHome(){const leagues=publicCompetitions("league");$("#homeDivisions").innerHTML=leagues.map(divisionCard).join("");const upcoming=state.fixtures.filter(f=>["scheduled","postponed"].includes(f.status)&&competition(f.competition_id)?.visible!==false).sort(dateAsc)[0];const fm=$("#homeFeature");if(upcoming){const h=club(upcoming.home_club_id),a=club(upcoming.away_club_id);fm.innerHTML=`<div class="feature-main"><p class="kicker">${esc(competitionLabel(upcoming.competition_id))}${upcoming.round_name?` · ${esc(upcoming.round_name)}`:""}</p><div class="match-teams"><div class="match-team">${clubMark(h)}<strong>${esc(h.name)}</strong></div><div class="match-score">VS<small>${esc(fmtDate(upcoming.kickoff_at))}</small></div><div class="match-team">${clubMark(a)}<strong>${esc(a.name)}</strong></div></div><div class="match-meta"><span>${esc(fmtTime(upcoming.kickoff_at))}</span><span>${esc(upcoming.venue||"Venue TBC")}</span></div></div><div class="feature-side"><p class="kicker">Fixture centre</p><h3>Plan the next matchday.</h3><p class="muted">See every confirmed fixture by division and tournament.</p><div class="button-row"><a class="button" href="fixtures.html">Open fixtures</a></div></div>`}else fm.innerHTML=`<div class="feature-main">${empty("No upcoming fixture published","The next confirmed match will appear here automatically.","NEXT")}</div><div class="feature-side"><p class="kicker">Admin managed</p><h3>Fixtures are ready to publish.</h3><p class="muted">Use the dashboard to add dates, venues, teams and competition rounds.</p><div class="button-row"><a class="button" href="admin.html">Open dashboard</a></div></div>`;
  const tableComp=leagues.find(c=>c.id==="mpl")||leagues[0];$("#homeTableLabel").textContent=`${tableComp?.short_name||"League"} table`;$("#homeTable").innerHTML=standingsTable(state.standings.filter(r=>r.competition_id===tableComp?.id),true);$("#homeNews").innerHTML=state.news.filter(n=>n.published!==false).sort((a,b)=>new Date(b.published_at)-new Date(a.published_at)).slice(0,3).map(newsCard).join("")||empty("No news published","Association stories will appear here.","NEWS");$("#homePartners").innerHTML=state.partners.filter(p=>p.active!==false).slice(0,4).map(partnerCard).join("")||empty("Partner space ready","Sponsors and partners can be added from the dashboard.","PARTNERS")}
function renderMatches(){filterButtons($("#matchFilters"),true);const items=filteredFixtures().filter(f=>["finished","live"].includes(f.status)&&(f.status==="live"||f.verified)).sort(dateDesc);$("#matchesList").innerHTML=items.map(matchCard).join("")||empty("No verified results","Completed matches will appear after results are confirmed.","FT");$("#matchCount").textContent=`${items.length} match${items.length===1?"":"es"}`}
function renderFixtures(){filterButtons($("#fixtureFilters"),true);const items=filteredFixtures().filter(f=>["scheduled","postponed","cancelled"].includes(f.status)).sort(dateAsc);$("#fixturesList").innerHTML=items.map(matchCard).join("")||empty("No fixtures published","Confirmed dates and venues will appear here.","FIX");$("#fixtureCount").textContent=`${items.length} fixture${items.length===1?"":"s"}`}
function renderStandings(){const leagues=publicCompetitions("league");if(state.competition==="all"||competition(state.competition)?.type!=="league")state.competition=leagues.find(c=>c.id==="mpl")?.id||leagues[0]?.id||"all";filterButtons($("#tableFilters"),false,"league");const c=competition(state.competition);$("#tableDivisionTitle").textContent=c?.name||"League table";$("#standingsMount").innerHTML=standingsTable(state.standings.filter(r=>r.competition_id===state.competition))+playoffPathway(c)}
function renderClubs(){filterButtons($("#clubFilters"),true);const search=$("#clubSearch"),q=(search?.value||"").trim().toLowerCase();let items=state.clubs.filter(c=>c.active!==false);if(state.competition!=="all"){const ids=new Set(state.entries.filter(e=>e.active!==false&&e.competition_id===state.competition).map(e=>e.club_id));items=items.filter(c=>ids.has(c.id))}if(q)items=items.filter(c=>[c.name,c.location,c.ground].some(v=>String(v||"").toLowerCase().includes(q)));$("#clubsGrid").innerHTML=items.map(clubCard).join("")||empty("No clubs found","Add clubs or change the selected competition.","CLUBS");const selected=state.competition==="all"?"all competitions":competition(state.competition)?.short_name||state.competition;$("#clubCount").textContent=`${items.length} club${items.length===1?"":"s"} · ${selected}`;if(search&&!search.dataset.bound){search.addEventListener("input",renderClubs);search.dataset.bound="true"}}
function renderNews(){filterButtons($("#newsFilters"),true);let items=state.news.filter(n=>n.published!==false);if(state.competition!=="all")items=items.filter(n=>!n.competition_id||n.competition_id===state.competition);items.sort((a,b)=>new Date(b.published_at)-new Date(a.published_at));$("#allNews").innerHTML=items.map(newsCard).join("")||empty("No news in this competition","Published stories will appear here.","NEWS")}
function renderCompetitions(){$("#allCompetitions").innerHTML=publicCompetitions("league").map(divisionCard).join("")||empty("No divisions visible","Divisions can be revealed from the dashboard.","DIV")}
function renderTournaments(){const groups=competitionGroups(publicCompetitions("league")).filter(g=>CHAMPIONSHIP_FAMILIES.has(g.id));const playoffCards=groups.map(g=>{const first=g.competitions[0],leaders=g.competitions.map(c=>({c,leader:leaderForCompetition(c)}));const outcome=g.id==="u19"?"Champion promoted to Super League":g.id==="mpl"?"Champion promoted to Super League":g.id==="super"?"Champion crowned · two clubs relegated · U19 and MPL champions promoted":"Division champion crowned";return`<article class="playoff-overview-card"><div class="playoff-overview-head"><div><span class="eyebrow">Division playoff</span><h3>${esc(g.label)}</h3></div><a class="text-link" href="standings.html?competition=${encodeURIComponent(first.id)}">Open tables →</a></div><div class="playoff-overview-leaders">${leaders.map(x=>`<div><small>${esc(streamLabel(x.c,g.id,g.competitions.length))}</small><strong>${x.leader.club?esc(x.leader.club.name):esc(x.leader.label)}</strong></div>`).join("")}</div><p>${esc(ruleSummary(first))}</p><span class="playoff-outcome">${esc(outcome)}</span></article>`}).join("");const items=publicCompetitions("tournament"),cupCards=items.map(c=>`<article class="tournament-card" style="--accent:${attr(c.accent||"#d8202f")}"><div class="tournament-accent"></div><div class="tournament-copy"><span class="status">${esc(c.short_name)}</span><h3>${esc(c.name)}</h3><p>${esc(c.description||"Cup competition details will be published soon.")}</p></div><div class="tournament-action"><a class="button secondary" href="fixtures.html?competition=${encodeURIComponent(c.id)}">View cup fixtures</a></div></article>`).join("");$("#tournamentList").innerHTML=`<section class="playoff-hub"><div class="section-head compact-head"><div><p class="kicker">League playoffs</p><h2 class="heading">Championship and movement pathway.</h2><p class="muted">Current leaders are provisional. This section does not create fixtures or confirm match dates.</p></div></div><div class="playoff-overview-grid">${playoffCards}</div></section><section class="cup-hub"><div class="section-head compact-head"><div><p class="kicker">Cup competitions</p><h2 class="heading">Published tournaments.</h2></div></div><div class="match-list">${cupCards||empty("No tournaments currently visible","Cup competitions will appear when an administrator reveals them.","CUP")}</div></section>`}
function renderPartners(){$("#partnersGrid").innerHTML=state.partners.filter(p=>p.active!==false).sort((a,b)=>num(a.display_order)-num(b.display_order)).map(partnerCard).join("")||empty("Partner directory ready","Sponsor and partner profiles can be published from the dashboard.","PARTNERS")}
function renderClub(){const key=new URLSearchParams(location.search).get("id");const c=state.clubs.find(x=>x.id===key||x.slug===key);const m=$("#clubProfile");if(!c){m.innerHTML=`<section class="section"><div class="container">${empty("Club not found","This club profile is unavailable.","404")}</div></section>`;return}const comps=entriesForClub(c.id).map(competition).filter(Boolean);let matches=state.fixtures.filter(f=>f.home_club_id===c.id||f.away_club_id===c.id);if(state.competition!=="all")matches=matches.filter(f=>f.competition_id===state.competition);matches=matches.sort(dateDesc).slice(0,8);const matchLabel=state.competition==="all"?"All competitions":competitionLabel(state.competition);m.innerHTML=`<section class="club-profile-hero"><div class="container club-profile-grid"><div class="profile-crest">${clubMark(c)}</div><div><p class="kicker">Club profile</p><h1 class="page-title">${esc(c.name)}</h1><p class="lead">${esc(c.description||"Club information will be published by the authorised administrator.")}</p><div class="mini-pills">${comps.map(x=>`<a class="mini-pill" href="${attr(competitionHref(x.id))}">${esc(x.short_name)}</a>`).join("")}</div></div></div></section><section class="section compact"><div class="container profile-details"><div class="info-panel"><span class="detail-label">Home ground</span><strong>${esc(c.ground||"TBC")}</strong></div><div class="info-panel"><span class="detail-label">Location</span><strong>${esc(c.location||"TBC")}</strong></div><div class="info-panel"><span class="detail-label">Founded</span><strong>${esc(c.founded_year||"TBC")}</strong></div></div></section><section class="section muted-section"><div class="container"><div class="section-head"><div><p class="kicker">Club match centre · ${esc(matchLabel)}</p><h2 class="heading">Fixtures and results.</h2></div></div><div class="match-list">${matches.map(matchCard).join("")||empty("No club matches published",state.competition==="all"?"Fixtures and results for this club will appear here.":`No ${matchLabel} fixtures or results are published for this club yet.`,"90")}</div></div></section>`}
function renderArticle(){const key=new URLSearchParams(location.search).get("id");const n=state.news.find(x=>x.id===key||x.slug===key);const m=$("#newsArticle");if(!n){m.innerHTML=`<section class="section"><div class="container">${empty("Article not found","This story is unavailable.","404")}</div></section>`;return}const body=String(n.body||n.excerpt||"").split(/\n{2,}/).filter(Boolean).map(p=>`<p>${esc(p).replace(/\n/g,"<br>")}</p>`).join("");m.innerHTML=`<article class="article-layout"><header class="article-header"><p class="kicker">${esc(n.category||"Football News")}</p><h1 class="heading">${esc(n.title)}</h1><p class="lead">${esc(n.excerpt||"")}</p><div class="news-meta" style="margin-top:22px"><span>${esc(n.competition_id?competitionLabel(n.competition_id):"MALFA")}</span><span>${esc(fmtDate(n.published_at))}</span></div></header>${n.image_url?`<img class="article-image" src="${attr(n.image_url)}" alt="">`:""}<div class="article-body">${body}</div></article>`}
function renderPage(){({home:renderHome,matches:renderMatches,fixtures:renderFixtures,standings:renderStandings,clubs:renderClubs,news:renderNews,competitions:renderCompetitions,tournaments:renderTournaments,partners:renderPartners,club:renderClub,article:renderArticle})[PAGE]?.();observe()}
let observer;function observe(){const els=$$(".reveal:not(.visible)");if(!("IntersectionObserver"in window)){els.forEach(e=>e.classList.add("visible"));return}observer||=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.08});els.forEach(e=>observer.observe(e))}
async function init(){renderHeader();renderFooter();await loadData();if(state.competition!=="all"&&!competition(state.competition))state.competition="all";renderPage()}
document.addEventListener("DOMContentLoaded",init);
